#ifndef INC_CONFIG_H_
#define INC_CONFIG_H_

#include "main.h"
#include "nrf24.h"

#define NO_OF_NODES_TO_MONITOR 3

extern const uint8_t THIS_NODE_NUM, TOTAL_NO_OF_NODES, THIS_NODE_ID, PREV_NODE_ID, NEXT_NODE_ID, LOCOMOTIVE_NODE_ID;
extern const uint8_t THIS_NODE_ADDRESS[5], *PREV_NODE_ADDRESS, NEXT_NODE_ADDRESS[5], *LOCOMOTIVE_NODE_ADDRESS;
extern const uint8_t NRF24_LOWER_NODE_RF_CHANNEL, NRF24_HIGHER_NODE_RF_CHANNEL, NRF24_LOCOMOTIVE_NODE_RF_CHANNEL,
		NRF24_RF_CHANNEL_MIN, NRF24_RF_CHANNEL_MAX;

extern const uint8_t NRF24_TX_PWR, NRF24_DATA_RATE, NRF24_AUTO_RETRY_DELAY, NRF24_AUTO_RETRY_COUNT;
extern const unsigned long TX_INTERVAL, SW_SAMPLING_INTERVAL;
#endif /* INC_CONFIG_H_ */
